language: ruby
rvm:
  - ruby-head
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-18mode
  - jruby-19mode
  - jruby-head
before_install:
 - gem update bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
